# Generated by Django 3.0.3 on 2020-05-10 21:18

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.polygon
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(default='untitled', max_length=50)),
                ('stream_url', models.TextField(default='unsetted')),
                ('region_of_interest', django.contrib.gis.db.models.fields.PolygonField(default=django.contrib.gis.geos.polygon.Polygon(((0, 0), (0, 0), (0, 0), (0, 0), (0, 0))), srid=4326)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'camera_list',
            },
        ),
        migrations.CreateModel(
            name='TrafficHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'traffic_history',
            },
        ),
    ]
